package com.example.footballapps.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "previous_match")
data class PreviousMatchLocal(
    @PrimaryKey
    @ColumnInfo(name = "id_event")
    val idEvent: String,
    @ColumnInfo(name = "date_event")
    val dateEvent: String?,
    @ColumnInfo(name = "date_event_local")
    val dateEventLocal: String?,
    @ColumnInfo(name = "id_away_Team")
    val idAwayTeam: String?,
    @ColumnInfo(name = "id_home_team")
    val idHomeTeam: String?,
    @ColumnInfo(name = "id_league")
    val idLeague: String?,
    @ColumnInfo(name = "id_soccer_XML")
    val idSoccerXML: String?,
    @ColumnInfo(name = "int_away_score")
    val intAwayScore: String?,
    @ColumnInfo(name = "int_away_shots")
    val intAwayShots: String?,
    @ColumnInfo(name = "int_home_score")
    val intHomeScore: String?,
    @ColumnInfo(name = "int_home_shots")
    val intHomeShots: String?,
    @ColumnInfo(name = "int_round")
    val intRound: String?,
    @ColumnInfo(name = "int_spectators")
    val intSpectators: String?,
    @ColumnInfo(name = "str_away_formation")
    val strAwayFormation: String?,
    @ColumnInfo(name = "str_away_goal_details")
    val strAwayGoalDetails: String?,
    @ColumnInfo(name = "strAwayLineupDefense")
    val strAwayLineupDefense: String?,
    @ColumnInfo(name = "strAwayLineupForward")
    val strAwayLineupForward: String?,
    @ColumnInfo(name = "strAwayLineupGoalkeeper")
    val strAwayLineupGoalkeeper: String?,
    @ColumnInfo(name = "strAwayLineupMidfield")
    val strAwayLineupMidfield: String?,
    @ColumnInfo(name = "strAwayLineupSubstitutes")
    val strAwayLineupSubstitutes: String?,
    @ColumnInfo(name = "strAwayRedCards")
    val strAwayRedCards: String?,
    @ColumnInfo(name = "strAwayTeam")
    val strAwayTeam: String?,
    @ColumnInfo(name = "strAwayYellowCards")
    val strAwayYellowCards: String?,
    @ColumnInfo(name = "strBanner")
    val strBanner: String?,
    @ColumnInfo(name = "strCircuit")
    val strCircuit: String?,
    @ColumnInfo(name = "strCity")
    val strCity: String?,
    @ColumnInfo(name = "strCountry")
    val strCountry: String?,
    @ColumnInfo(name = "strDate")
    val strDate: String?,
    @ColumnInfo(name = "strDescriptionEN")
    val strDescriptionEN: String?,
    @ColumnInfo(name = "strEvent")
    val strEvent: String?,
    @ColumnInfo(name = "strEventAlternate")
    val strEventAlternate: String?,
    @ColumnInfo(name = "strFanart")
    val strFanart: String?,
    @ColumnInfo(name = "strFilename")
    val strFilename: String?,
    @ColumnInfo(name = "strHomeFormation")
    val strHomeFormation: String?,
    @ColumnInfo(name = "strHomeGoalDetails")
    val strHomeGoalDetails: String?,
    @ColumnInfo(name = "strHomeLineupDefense")
    val strHomeLineupDefense: String?,
    @ColumnInfo(name = "strHomeLineupForward")
    val strHomeLineupForward: String?,
    @ColumnInfo(name = "strHomeLineupGoalkeeper")
    val strHomeLineupGoalkeeper: String?,
    @ColumnInfo(name = "strHomeLineupMidfield")
    val strHomeLineupMidfield: String?,
    @ColumnInfo(name = "strHomeLineupSubstitutes")
    val strHomeLineupSubstitutes: String?,
    @ColumnInfo(name = "strHomeRedCards")
    val strHomeRedCards: String?,
    @ColumnInfo(name = "strHomeTeam")
    val strHomeTeam: String?,
    @ColumnInfo(name = "strHomeYellowCards")
    val strHomeYellowCards: String?,
    @ColumnInfo(name = "strLeague")
    val strLeague: String?,
    @ColumnInfo(name = "strLocked")
    val strLocked: String?,
    @ColumnInfo(name = "strMap")
    val strMap: String?,
    @ColumnInfo(name = "strPoster")
    val strPoster: String?,
    @ColumnInfo(name = "strResult")
    val strResult: String?,
    @ColumnInfo(name = "strSeason")
    val strSeason: String?,
    @ColumnInfo(name = "strSport")
    val strSport: String?,
    @ColumnInfo(name = "strTVStation")
    val strTVStation: String?,
    @ColumnInfo(name = "strThumb")
    val strThumb: String?,
    @ColumnInfo(name = "strTime")
    val strTime: String?,
    @ColumnInfo(name = "strTimeLocal")
    val strTimeLocal: String?,
    @ColumnInfo(name = "strTweet1")
    val strTweet1: String?,
    @ColumnInfo(name = "strTweet2")
    val strTweet2: String?,
    @ColumnInfo(name = "strTweet3")
    val strTweet3: String?,
    @ColumnInfo(name = "strVideo")
    val strVideo: String?
)